---
title: "hands on exercise 1"
author: "XU LIN"
date: "2023-11-18"
---

##Overview

This is the overview paragraph.

##Getting Started

This is the getting start paragraph

```{r}
pacman::p_load(sf, tidyverse)
```

```{r}
mpsz <- st_read(dsn = "data/geospatial", layer = "MP14_SUBZONE_WEB_PL")
```

```{r}
preschool3414 <- st_transform(preschool, crs = 3414)
```

```{r}
listings <- read_csv("hands-on exercise 1/data/aspatial/listings.csv")
```

```{r}
list(listings)
```

```{r}
listings_sf <- st_as_sf(listings, coords = c("longitude", "latitude"), crs=4326) %>% st_transform(crs = 3414)
```

```{r}
glimpse(listings_sf)
```

```{r}
buffer_cycling <- st_buffer(cyclingpath, dist=5, nQuadSegs = 30)
```

```{r}
buffer_cycling$AREA <- st_area(buffer_cycling)
```

```{r}
sum(buffer_cycling$AREA)
```

```{r}
mpsz3414$`PreSch Count`<- lengths(st_intersects(mpsz3414, preschool3414))
```

```{r}
summary(mpsz3414$`PreSch Count`)
```

```{r}
top_n(mpsz3414, 1, `PreSch Count`)
```

```{r}
mpsz3414$Area <- mpsz3414 %>% st_area()
```

```{r}
mpsz3414 <- st_set_crs(mpsz, 3414)
```

```{r}
mutate(`PreSch Density` = `PreSch Count` * Area * 1000000)
```

```{r}
hist(mpsz3414$`PreSch Density`)
```

```{r}
ggplot(data=mpsz3414, aes(x= as.numeric(`PreSch Density`)))+ geom_histogram(bins=20, color="black", fill="light blue") + labs(title = "Are pre-school even distributed in Singapore?", subtitle= "There are many planning sub-zones with a single pre-school, on the other hand, nthere are two planning sub-zones with at least 20 pre-schools", x = "Pre-school density (per km sq)", y = "Frequency")
```

```{r}
ggplot(data=mpsz3414, aes(y = `PreSch Count`, x= as.numeric(`PreSch Density`)))+ geom_point(color="black", fill="light blue") + xlim(0, 40) + ylim(0, 40) + labs(title = "", x ="Pre-school density (per km sq)", y ="Pre-school count")
```
